using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace deeplinkUtil
{
    public class URLSchemes
    {
        public string FBscheme = @"fb://";
        public string GPscheme = @"gplus://";
        public string TWTRscheme = @"twitter://user?screen_name=";
        public string IgANDRDscheme = @"intent://instagram.com/_u/|/#Intent;package=com.instagram.android;scheme=https;end";
        public string IgAPPLscheme = @"instagram://user?username=";

        ///standard link
        //https://www.instagram.com/belaircantina/
        ///instagram android intent
        //intent://instagram.com/_u/belaircantina/#Intent;package=com.instagram.android;scheme=https;end
        ///instagram apple deeplink
        //instagram://user?username=belaircantina

        ///FACEBOOK URL SCHEMES
        //{https://m.facebook.com}/pages/launchpoint/admin_invites/
        //{https://m.facebook.com}/pages/launchpoint/liked_pages/
        //{https://m.facebook.com}/pages/launchpoint/owned_pages/
        //{https://m.facebook.com}/pages/launchpoint/pending_invites/

        //fb-service://limit_friend_requests

        //fb://about
        //fb://account/recovery
        //fb://account_settings
        //fb://add_services
        //fb://ads/preferences/?tracking=%s
        //fb://ads_experience/?id=%s
        //fb://adsmanager/%s/insights/%s
        //fb://adsmanager/{account}/insights/{campaignGroup}
        //fb://adsmanager/image/select/%s
        //fb://adsmanager/image/select/{page}
        //fb://albums
        //fb://albums/%s
        //fb://albums_edit_flow
        //fb://ama?entryPoint=%s&targetURI=%s
        //fb://anniversary_video?campaign_id=%s
        //fb://anniversary_video?campaign_id={campaign_id}
        //fb://a-place-for/%s
        //fb://app_discovery_lite?appInviteId=%s&referrer=%s
        //fb://app_discovery_lite?packageName=%s&referrer=%s
        //fb://app_section/%s/%s
        //fb://appcenter
        //fb://appcenter/detail?app_id=%s
        //fb://appfeed
        //fb://appinvites/
        //fb://background_location/nux?source=%s&redirect_after_accept=%s&informational=%s
        //fb://background_location/nux?source=%s&redirect_after_accept=%s&nux_type=%s
        //fb://background_location/settings
        //fb://background_location/settings?theme=%s
        //fb://backstage/reply/
        //fb://backstage/stack/
        //fb://birthday_card/
        //fb://birthdays
        //fb://bookmarks
        //fb://bookmarks_section
        //fb://boost_event/?page_id=%s&graphql_story_id=%s&legacy_story_id=%s&promotion_target_id=%s&placement_extra=%s&referral=%s
        //fb://boost_post/?page_id=%s&graphql_story_id=%s&legacy_story_id=%s&referral=%s
        //fb://browser_extensions/commerce/?page_id=%s&extension=%s
        //fb://cardboard
        //fb://codegenerator
        //fb://collection/%s/%s/%s
        //fb://commerce/admin/products/%s/edit
        //fb://commerce/admin/products/add
        //fb://commerce/admin/shop/%s/add
        //fb://commerce/admin/shop/%s/edit
        //fb://commerce/collectionview/%s
        //fb://commerce/collectionview/ad/%s
        //fb://commerce/products/%s
        //fb://commerce/products/%s/edit
        //fb://commerce/products/<p$1>
        //fb://commerce/products/add
        //fb://commerce/shop/%s
        //fb://commerce_inventory?groupID=%s
        //fb://composer/?view={%s}&profile_type={%s -1}&target={%s -1}
        //fb://composer/topic_selector
        //fb://coverphoto
        //fb://cta_promotion?page_id=%s&source=%s&referral=%s&restore_saved_settings=%s
        //fb://data_savings_mode_settings
        //fb://data_savings_mode_settings/?source=bar
        //fb://data_savings_mode_settings/?source=bookmarks
        //fb://data_savings_nux
        //fb://data_savings_quick_promotion
        //fb://data_savings_quick_promotion_dialog
        //fb://data_sensitivity_settings
        //fb://data_sensitivity_settings/?source=bookmarks
        //fb://dbl_loggedin_settings
        //fb://dialtone_info_screen
        //fb://donate/?fundraiser_campaign_id=%1$s&action_type=%2$s
        //fb://donate/?fundraiser_campaign_id=%1$s&post_id=%2$s
        //fb://donate/?fundraiser_campaign_id=%1$s&post_id=0
        //fb://donate/?fundraiser_campaign_id=%1$s&source=%2$s
        //fb://donate?source=%1$s&fundraiser_campaign_id=%2$s
        //fb://donate_create
        //fb://donate_create/?fundraiser_charity_id=%1$s&source=%2$s
        //fb://donate_create/?source=%1$s
        //fb://donate_invite/?fundraiser_campaign_id=%1$s
        //fb://donate_invite/?fundraiser_campaign_id=%1$s&source=%2$s
        //fb://donate_invite/?fundraiser_campaign_id=%1$s&source=%2$s&is_creator=%3$s
        //fb://donate_single_click_invite/?fundraiser_campaign_id=%1$s
        //fb://donate_single_click_invite/?fundraiser_campaign_id=%1$s&source=%2$s
        //fb://editor?entry_point=%s
        //fb://event/%s
        //fb://event/%s/extendedinvite
        //fb://event/%s/invite
        //fb://event/%s/invitegroup/%s
        //fb://event/%s/messagefriends
        //fb://event/%s/messagefriends/asgroup
        //fb://event_collection
        //fb://event_creation
        //fb://event_creation/
        //fb://event_creation/%s
        //fb://event_creation/{#%s}
        //fb://event_creation/categories
        //fb://event_creation/notification?story_cache_id=%s
        //fb://event_creation/prefill/%s
        //fb://event_discovery
        //fb://events
        //fb://events/{%s}/reaction
        //fb://events/section?section_name=%s
        //fb://events/section?section_name={%s}
        //fb://events_suggestion?cuttype={%s}
        //fb://faceweb/f?href=
        //fb://faceweb/f?href=%2Ffriends%2Fcenter%2Ffriends%2F
        //fb://faceweb/f?href=%2Fhelp%2Fwork
        //fb://faceweb/f?href=%2Flegal%2FFB_Work_Terms
        //fb://faceweb/f?href=%2Fnearby_info%2Fmanage_hidden_pages
        //fb://faceweb/f?href=%2Fonavo/promotion/install
        //fb://faceweb/f?href=%2Fpolicies
        //fb://faceweb/f?href=%2Fprivacy
        //fb://faceweb/f?href=%2Fprivacy%2Ftouch%2Ftimeline_and_tagging
        //fb://faceweb/f?href=%s
        //fb://faceweb/f?href=%s&force_faceweb=true
        //fb://faceweb/f?href=/%s/legacy_contact
        //fb://faceweb/f?href=/%s/year/%d
        //fb://faceweb/f?href=/ads/manager
        //fb://faceweb/f?href=/commerce/contact-merchant/dialog/?product_item_id=%s
        //fb://faceweb/f?href=/coupons/info/?coupon_id=%s
        //fb://faceweb/f?href=/event/%s/madminpanel/pending
        //fb://faceweb/f?href=/follow/feedsources?source=bookmark
        //fb://faceweb/f?href=/groups
        //fb://faceweb/f?href=/instant_article/publisher_ad_about
        //fb://faceweb/f?href=/media/set/?set=ft.%s
        //fb://faceweb/f?href=/pages/create/?ref_type=android_timeline
        //fb://faceweb/f?href=/pages/create/?ref_type=page_more_menu
        //fb://faceweb/f?href=/pages/create/?ref_type=pages_nav_home
        //fb://faceweb/f?href=/pages/messaging/action/compose/?post_id=%s
        //fb://faceweb/f?href=/pages/place_claim/entry_redirect/?page_id=%s
        //fb://faceweb/f?href=/profile/intro/edit/about
        //fb://faceweb/f?href=/profile/intro/edit/links
        //fb://faceweb/f?href=/send_page_invite/?pageid=%s&reference=pages_nav_home
        //fb://faceweb/f?href=/timeline/friend_list_view/?profile_id=%s
        //fb://faceweb/f?href=https://m.facebook.com/onthisday/notification/settings/?source=permalink
        //fb://faceweb/f?href=https://m.facebook.com/onthisday/preferences/?source=permalink
        //fb://facewebmodal/f?href=%s
        //fb://fb_photos_picker
        //fb://fb_photos_picker/?campaign=%s
        //fb://feed
        //fb://feed_awesomizer
        //fb://feed_awesomizer/connections
        //fb://feed_awesomizer/following
        //fb://feed_awesomizer/see_first
        //fb://feed_awesomizer/unfollowed
        //fb://feed_settings
        //fb://feed_switcher?switcher_item_id={%s}
        //fb://findfriends
        //fb://findfriends/browser
        //fb://findfriends/learn_more
        //fb://findfriends?ci_flow=%s
        //fb://findfriends?ci_flow=%s&ccu_ref=%s&force_show_legal_screen=true
        //fb://findfriends?ci_flow=%s&force_show_legal_screen=true
        //fb://findfriends?ci_flow=CONTINUOUS_SYNC&ccu_ref=%s&force_show_legal_screen=true
        //fb://findfriends?ci_flow=CONTINUOUS_SYNC&force_show_legal_screen=true
        //fb://free_facebook_settings
        //fb://free_fb_invite
        //fb://friending/suggestion/%s/%s
        //fb://friending_possibilities?location=%s
        //fb://friendlist/%s
        //fb://friends/
        //fb://friends/accept/notifications
        //fb://friends/center
        //fb://friends/center?fc_tab=%s
        //fb://friends/center?source_ref=%s
        //fb://friends/center?source_ref=%s&fc_tab=%s
        //fb://friends/center?source_ref=%s&fc_tab=requests&user_id=%s&name=%s&profile_pic=%s
        //fb://friends/immersivepymk
        //fb://friends/requests/
        //fb://friends/requests_tab
        //fb://friendship
        //fb://friendship/%s/%s
        //fb://friendsnearby/profile?fbid=%s&source=%s
        //fb://friendsnearby?source=%s
        //fb://friendsnearby_invite?selected=%s&excluded=%s
        //fb://getgames
        //fb://gift/receive?gid=%s
        //fb://goodfriends/camera
        //fb://goodfriends/nux_flow
        //fb://goodfriends/select_audience
        //fb://graphsearch
        //fb://graphsearch/query?q=%s&display_style=%s&title=%s
        //fb://group/%s
        //fb://group/%s/yourposts
        //fb://group/{%s}/permalink/{%s}/comment/{%s}
        //fb://groups/addtogroups/%s?profile_name=%s
        //fb://groups/create
        //fb://groups/create?ref=%s
        //fb://groups/createtab
        //fb://groups/discover
        //fb://groups/discover/categories
        //fb://groups/discover/category?id={%s}
        //fb://groups/discover/tag?id=%s
        //fb://groups/discover/tag?id={%s}
        //fb://groups/events/{%s}
        //fb://groups/gridtab
        //fb://groups/members/{%s}
        //fb://groups/photos/{%s}
        //fb://groups/settings/{%s}
        //fb://groups/suggestions?source=%s
        //fb://groups/suggestions?source={%s}
        //fb://groups_hub_search
        //fb://groups_tab
        //fb://gv/editor/card?campaign_id=%s&campaign_type=%s&direct_source=%s
        //fb://gv/share?campaign_id=%s&campaign_type=%s&source=%s&direct_source=%s&share_preview=%s&share_autofill=%s&share_placeholder=%s
        //fb://hashtag/%s?name=%s&id=%s
        //fb://help
        //fb://id_backed_privacy_checkup/checkup_id=%s
        //fb://id_backed_privacy_checkup_react/?checkup_id=%s
        //fb://instant_articles
        //fb://instant_shopping_catalog/?catalog_id={%s -1}&catalog_view={%s -1}&product_id={%s -1}&product_view={%s -1}
        //fb://instant_shopping_catalog/?catalog_id={%s}
        //fb://iorg/basicServices
        //fb://jobApplication
        //fb://language_switch
        //fb://languages/?locale=%s
        //fb://lead_gen/?lead_gen_data_id={%s -1}&ad_id={%s -1}
        //fb://leadgen/?lead_gen_data_id={%s -1}&ad_id={%s -1}
        //fb://link_fb_invite
        //fb://live_sport_event/%s/%s
        //fb://local_awareness_promotion/?page_id=%s&source=%s&referral=%s&restore_saved_settings=%s
        //fb://localsell_home/?tabIndex=%s&referralSurface=%s
        //fb://location_settings
        //fb://loginapprovalspush
        //fb://look_now
        //fb://maps
        //fb://marketplace_activity?id=%s
        //fb://marketplace_category_menu
        //fb://marketplace_category_search
        //fb://marketplace_composer/?assetIDs=%s
        //fb://marketplace_editcomposer/?storyID=%s&referralSurface=%s
        //fb://marketplace_forsalegroupshome
        //fb://marketplace_forsalegroupshome_story
        //fb://marketplace_home
        //fb://marketplace_initial_message
        //fb://marketplace_location
        //fb://marketplace_message
        //fb://marketplace_message/?threadID=%s
        //fb://marketplace_message/?threadID=%s&assetIDs=%s
        //fb://marketplace_message/?threadID=%s&referralSurface=%s
        //fb://marketplace_notifications
        //fb://marketplace_product_details
        //fb://marketplace_product_details?id=%s&referralSurface=%s
        //fb://marketplace_product_details_from_post_id/?post_id=%s
        //fb://marketplace_product_message_threads
        //fb://marketplace_product_message_threads/?productTitle=%s&productID=%s&referralSurface=%s
        //fb://marketplace_profile?id=%s
        //fb://marketplace_saved
        //fb://marketplace_saved_search_results
        //fb://marketplace_search
        //fb://marketplace_your_items
        //fb://marketplacesearch
        //fb://mediaset/brpi.%s
        //fb://mediaset/brpo.%s
        //fb://mediaset/oa.%s
        //fb://mediaset/pb.%s
        //fb://menu_management?page_id=%s
        //fb://messaging
        //fb://messaging/
        //fb://messaging/%s
        //fb://messaging/compose/
        //fb://messaging/compose/%s
        //fb://messaging/compose/new
        //fb://messaging/compose/new/group
        //fb://messaging/groupthreadfbid/
        //fb://messaging/groupthreadfbid/%s
        //fb://messaging/thread/thread?id=
        //fb://messaging/thread/thread?id=%s
        //fb://messaging_tab
        //fb://moments/upsell
        //fb://multi_post_story/%s
        //fb://multi_post_story/{%s}
        //fb://multi_post_story/{%s}?name={%s}
        //fb://native_album/%s
        //fb://native_article?article={%s}
        //fb://native_article?article={%s}&canonical={%s}
        //fb://native_article?article={%s}&canonical={%s}&saved={%s}
        //fb://native_document/?id={%s -1}
        //fb://native_note/{%s}
        //fb://native_post/%s?fallback_url=%s
        //fb://native_post/%s?story_cache_id=%s
        //fb://nativename
        //fb://nearby
        //fb://nearby/?wifi=1
        //fb://nearby/search
        //fb://nearby/subcategory
        //fb://nearbyInfoSettings
        //fb://newContactPoint
        //fb://note/%s
        //fb://notification_settings
        //fb://notification_settings_alerts
        //fb://notifications
        //fb://notifications_friending
        //fb://notifications_tab
        //fb://now/
        //fb://nt/shell
        //fb://nux/profile_picture?external_photo_source=%s
        //fb://offers/barcode_fullscreen/?title=%s&extra_image_url=%s
        //fb://offers/detail/?coupon_id=%s
        //fb://offers/detail/?offer_claim_id=%s
        //fb://offers/detail/?offer_id=%s&share_id=%s&notif_trigger=%s&notif_medium=%s&rule=%s
        //fb://offers/detail/?offer_id=%s&share_id=%s&redirect=%s
        //fb://offers/detail/view/?offer_view_id=%s&share_id=%s&notif_trigger=%s&notif_medium=%s&rule=%s
        //fb://offers/detail/view/?offer_view_id=%s&share_id=%s&redirect=%s
        //fb://offers/detail/view/?offer_view_id=%s&share_id=%s&redirect=%s&claim_type=%s
        //fb://offers/detail/view/?offer_view_id=%s&share_id=%s&redirect=%s&offer_should_claim=%s
        //fb://offers/wallet
        //fb://offersite/detail/?offer_id=%s&share_id=%s&site_uri=%s&title=%s
        //fb://offersite/detail/?offer_id=%s&share_id=%s&site_uri=%s&title=%s&notif_trigger=%s&notif_medium=%s&rule=%s
        //fb://offersite/detail/?offer_id=%s&share_id=%s&site_uri=%s&title=%s&offer_code=%s
        //fb://offersite/detail/?offer_id=%s&share_id=%s&site_uri=%s&title=%s&offer_code=%s&notif_trigger=%s&notif_medium=%s&rule=%s
        //fb://offersite/detail/view/?offer_view_id=%s&share_id=%s&site_uri=%s&claim_type=%s
        //fb://offersite/detail/view/?offer_view_id=%s&share_id=%s&site_uri=%s&title=%s
        //fb://offersite/detail/view/?offer_view_id=%s&share_id=%s&site_uri=%s&title=%s&notif_trigger=%s&notif_medium=%s&rule=%s
        //fb://offersite/detail/view/?offer_view_id=%s&share_id=%s&site_uri=%s&title=%s&offer_code=%s
        //fb://offersite/detail/view/?offer_view_id=%s&share_id=%s&site_uri=%s&title=%s&offer_code=%s&claim_type=%s
        //fb://offersite/detail/view/?offer_view_id=%s&share_id=%s&site_uri=%s&title=%s&offer_code=%s&notif_trigger=%s&notif_medium=%s&rule=%s
        //fb://online
        //fb://onthisday?source=%s
        //fb://onthisday?source=%s&campaign_id=%s&story_id=%s
        //fb://page/%s
        //fb://page/%s/admin_feed
        //fb://page/%s/admin_stories
        //fb://page/%s/album_list
        //fb://page/%s/call_to_action
        //fb://page/%s/child_locations
        //fb://page/%s/contactinbox
        //fb://page/%s/events_list
        //fb://page/%s/info
        //fb://page/%s/invite_friends_to_like_page
        //fb://page/%s/offers
        //fb://page/%s/pendingedits
        //fb://page/%s/reaction
        //fb://page/%s/recommendations
        //fb://page/%s/residence
        //fb://page/%s/scheduled_posts
        //fb://page/%s/service/%s
        //fb://page/%s/services_list
        //fb://page/%s/suggestedit?entry_point=%s
        //fb://page/%s/timeline
        //fb://page/%s/videohub
        //fb://page/%s/videolist?page_id=%s&source=%s
        //fb://page/%s/vistor_posts
        //fb://page/{%s}/tab/{%s}
        //fb://page/{%s}/videohub
        //fb://page/{%s}/videolist?page_id={%s}&source={%s}
        //fb://page/create_new_page
        //fb://page/messages/%s
        //fb://page/videolist?page_id=%s&source=%s
        //fb://page/videolist?page_id={%s}&source={%s}
        //fb://page/view_album/%s
        //fb://page_like_promotion/?page_id=%s&source=%s&referral=%s&restore_saved_settings=%s
        //fb://page_link_menu_management?page_id=%s
        //fb://pages
        //fb://pages/?category=%s
        //fb://pages/comments/%s
        //fb://pages/launchpoint
        //fb://pages/messaging/private_reply/dialog/%s/%s
        //fb://payment_settings
        //fb://payments/sampleflows
        //fb://photo/%s
        //fb://photo/%s/?set=%s
        //fb://photo_checkup/?source=%s&checkup_type=%s
        //fb://photo_menu/?page_id=%s
        //fb://photo_menu/add/?page_id=%s
        //fb://photosbycategory/?page_id=%s
        //fb://pivhelp
        //fb://place/creation
        //fb://placefeed?placeid=%s&surface=%s
        //fb://placefeed?placeid=%s&surface=%s&placename=%s
        //fb://placefeed?placeid=%s&surface=%s&placename=%s&wildcard=%s
        //fb://placelist_map
        //fb://platform_first_party
        //fb://pokes
        //fb://policies
        //fb://post/%s
        //fb://privacy_checkup/?source=%s
        //fb://privacy_review_lightweight/?checkup_type=%s
        //fb://profile
        //fb://profile/%s
        //fb://profile/%s/activitylog
        //fb://profile/%s/activitylog_search
        //fb://profile/%s/activitylog_search/%s
        //fb://profile/%s/friends/%s
        //fb://profile/%s/friends/%s?source_ref=%s
        //fb://profile/%s/info/expanded
        //fb://profile/%s/info/inner
        //fb://profile/%s?skip_popup=true
        //fb://profile/?id={profileId}&profile_type=person&intro_card=edit_featured_photos
        //fb://profile/info_request/%s/%s
        //fb://profile/section_stories/%d/%d
        //fb://profile/video/pick_thumbnail
        //fb://profile?frame_id={%s}&entry_point={%s}
        //fb://profile_qr?source=%s
        //fb://profileInfoUpdate?is_minor_user={!%s false}
        //fb://profilepictureupload
        //fb://profileshare/immersive
        //fb://promote_product/?page_id=%s&promotion_target_id=%s&referral=%s
        //fb://prompt/{%s}invite
        //fb://qp/%s?data=%s&fallback_url=%s
        //fb://qp/%s?fallback_url=%s
        //fb://qrcodelogin/?info={%s}
        //fb://reaction/session/%s/chrome
        //fb://reaction-demo
        //fb://redspace
        //fb://redspace/friends/overflow
        //fb://redspace/visitors
        //fb://registration
        //fb://reviews/?page_id=%s
        //fb://reviews/?review_id=%s
        //fb://reviews/?user_id=%s
        //fb://safetycheck?crisisID=%s
        //fb://salegroups
        //fb://samplernintegration
        //fb://saved
        //fb://saved/?section_name=%s&referer=%s
        //fb://saved/?section_name={%s}&referer={%s}
        //fb://search_typeahead_results/?module=MarketplaceSearch
        //fb://settings
        //fb://sg/fundraiser/?source=%1$s&fundraiser_campaign_id=%2$s
        //fb://shops
        //fb://social_search_conversion?post_id=%s&entry_point=%s&funnel_logging_tags=%s
        //fb://sports/%s
        //fb://sports_dashboard
        //fb://sports_league/%s
        //fb://stack/
        //fb://stack_camera/
        //fb://stack_import/
        //fb://stack_story/{id}
        //fb://store_locator/?north=%s&west=%s&south=%s&east=%s&ad_id=%s&page_set_id=%s&parent_page_id=%s
        //fb://story/%s/%s
        //fb://storygallerysurvey
        //fb://structured_menu/?page_id=%s
        //fb://topic_feeds_customization
        //fb://trust/afro/?hideable_token=%s&story_graphql_token=%s&initial_action=%s&story_location=%s&tracking=%s
        //fb://trust/afro/?reportable_ent_graphql_id=%s&initial_action=%s&story_location=%s
        //fb://trust/afro/?reportable_ent_token=%s&initial_action=%s&story_location=%s
        //fb://video/%s?source_url=%s
        //fb://video/?href={href}
        //fb://video/?id={%s}
        //fb://video/{%s}?source_url={href}
        //fb://video_home
        //fb://video_home/guide
        //fb://video_notification/%s
        //fb://videochannel?id=%s
        //fb://website_promotion/?page_id=%s&source=%s&referral=%s&restore_saved_settings=%s
        //fb://webview/?url={%s}
        //fb://work_groups_tab
        //fb://zero_dialog
    }
}
